- src/main/scala/com/github/johnynek/paiges/Doc.scala
- src/test/scala/com/github/johnynek/paiges/PaigesTest.scala
This seems to really improve efficiency and more closely model the haskell approach.
As a side-effect (ba-dum-bum), we can render easily to a `Stream[String]` which allows the caller to not have to materialize a giant `String` as a copy if they are just going to write it anyway.
cc @non
> Use Stream internally to be lazier

- src/main/scala/com/github/johnynek/paiges/Doc.scala
- src/test/scala/com/github/johnynek/paiges/JsonTest.scala
- src/test/scala/com/github/johnynek/paiges/PaigesTest.scala
Here I add a combinator (spaceGroup) which I *think* obeys the laws that it needs to in order to use with Union (namely that flatten of the union gives the same thing), but is useful for code situations where you want to continue on the line only if a whole block fits.
cc @non review?
> Show a basic Json example, add a new combinator for code

- src/main/scala/com/github/johnynek/paiges/Doc.scala
- src/test/scala/com/github/johnynek/paiges/JsonTest.scala
- src/test/scala/com/github/johnynek/paiges/PaigesTest.scala
.group really is all you have (or fancy ways to construct it) to keep the invariant that the algorithm leverages. In any case, I didn't need it since `spaceGroup(d) == group(Doc.line ++ d)` so why not use that directly.
> Remove spaceGroup. Sorry, it was late

- src/main/scala/com/github/johnynek/paiges/Doc.scala
- src/test/scala/com/github/johnynek/paiges/JsonTest.scala
- src/test/scala/com/github/johnynek/paiges/PaigesTest.scala
Removes the implicit from `String`, converts `++` to `+:`, adds `String` variants of many `Doc` methods.
> Clean up the API a bit

- README.md
- core/src/main/scala/com/github/johnynek/paiges/Doc.scala
- core/src/test/scala/com/github/johnynek/paiges/Generators.scala
- core/src/test/scala/com/github/johnynek/paiges/PaigesTest.scala
This fixes maxWidth to obey the laws, which allows us to strengthen the equality law. This led us to discover another bug with the comparison:
```
spaceOrLine.group == spaceOrLine
```
but that is currently false. I added the test to "hard union cases", which are commented out.
> Fix maxWidth find more comparison examples

- core/src/main/scala/com/github/johnynek/paiges/Doc.scala
- core/src/test/scala/com/github/johnynek/paiges/PaigesTest.scala
Previously Doc.text did not handle newlines correctly in some
cases. For example, multiple newlines would be collapsed into one
newline. Similarly, I think trailing newlines were also discarded.
This code is slightly more imperative, but should do the right thing
in all cases, and also be relatively efficient.
I added a law to ensure that:
Doc.text(s).render(0) = s
> Fix Doc.text() parsing errors.

- cats/src/main/scala/com/github/johnynek/paiges/instances.scala
- core/src/main/scala/com/github/johnynek/paiges/Doc.scala
- core/src/test/scala/com/github/johnynek/paiges/Generators.scala
- core/src/test/scala/com/github/johnynek/paiges/JsonTest.scala
- core/src/test/scala/com/github/johnynek/paiges/PaigesTest.scala
This method adds good Scaladoc comments to every method in Doc. It
also removes/renames some methods to try to give a slightly better
user-experience. It is relatively opinionated.
The companion object of Doc still needs some work, and we probably
want to split up Doc.scala, but I'm pushing this now to get feedback.
> First pass at polishing.

- core/src/main/scala/com/github/johnynek/paiges/Chunk.scala
- core/src/main/scala/com/github/johnynek/paiges/Doc.scala
- core/src/test/scala/com/github/johnynek/paiges/PaigesTest.scala
This give you the ability to avoid the branching code, which can blow up for very (10k) wide widths due to stack overflows.
Since very wide widths are not the use case of this code, I think we are mostly okay with not solving the stack overflow for such unrealistic widths.
Another solution would be to check if the width is say bigger than 1000, then check if it is bigger than the max, which is safe, and if it is bigger than the max, we can use the stack safe `renderWide` method and get the same result. This will often in practice solve the problem but we should probably punt for now since I think all the main usability SOEs are handled.
> Make maxWidth stack safe and add renderTall and renderWide

- benchmark/src/main/scala/Benchmark.scala
- core/src/main/scala/com/github/johnynek/paiges/Chunk.scala
- core/src/main/scala/com/github/johnynek/paiges/Doc.scala
It occurred to me: we already right-associate as part of the stack safety in flatten and flattenOption. As a result, the left side of a Union is already right associated no matter what we do. This property (and the fact that we unwind in the rendering loops already) breaks any O(N^2) performance.
I verified that with some benchmarks:
```
before:
[info] Benchmark                    (size)   Mode  Cnt      Score       Error   Units
[info] PaigesBenchmark.docConcat         1  thrpt    3   7271.123 ±  3786.344  ops/ms
[info] PaigesBenchmark.docConcat        10  thrpt    3   1127.478 ±   566.950  ops/ms
[info] PaigesBenchmark.docConcat       100  thrpt    3     27.731 ±    12.220  ops/ms
[info] PaigesBenchmark.docConcat      1000  thrpt    3      0.196 ±     0.012  ops/ms
[info] …
```
> Remove right-association in concat

- core/src/main/scala/com/github/johnynek/paiges/Chunk.scala
- core/src/main/scala/com/github/johnynek/paiges/Doc.scala
- core/src/main/scala/com/github/johnynek/paiges/DocTree.scala
- core/src/test/scala/com/github/johnynek/paiges/Generators.scala
- core/src/test/scala/com/github/johnynek/paiges/PaigesTest.scala
This adds two features seen in the haskell implementations of this paper:
1. lineBreak: this is a newline that is flattened to empty. This is actually present in wl-pprint, lending credence to the idea that this is the main custom flattening, but the code *seems* to imply other flattenings would be possible to support.
2. align: which sets the nesting to the current position. This is implemented directly rather than bases on two other combinators in wl-pprint. I did this because those other two combinators, while indeed more general complicate implementation and I couldn't clearly see the value like I could with align. Since we would still have alight later, we retain the option of adding those combinators at needed in the future.
As part of doing this I added a few new laws and found a …
> Add lineBreak and align

- core/src/main/scala/com/github/johnynek/paiges/Doc.scala
- core/src/test/scala/com/github/johnynek/paiges/Generators.scala
- core/src/test/scala/com/github/johnynek/paiges/JsonTest.scala
- core/src/test/scala/com/github/johnynek/paiges/PaigesTest.scala
- docs/src/main/tut/intro.md
Addresses #27 and @olafurpg's suggestion: https://github.com/johnynek/paiges/pull/29#discussion_r110709957
I didn't exactly rename `lineBreak` to `lineOrEmpty` since it is not actually a union. I added `lineOrEmpty = lineBreak.grouped`. The bare `lineBreak` is a bit confusing without `.grouped` in the picture, since in that case `line == lineOrEmpty`. This brings up a weird issue.
`line.compare(lineBreak) == 0` since indeed they do render identically. But actually `line.grouped.compare(lineBreak.grouped) == 1`.
So, you have a case where `a == b` but `f(a) != f(b)`. Which seems like a bug to me.
> Rename some methods

- core/src/main/scala/com/github/johnynek/paiges/Chunk.scala
- core/src/main/scala/com/github/johnynek/paiges/Doc.scala
- core/src/main/scala/com/github/johnynek/paiges/DocTree.scala
- core/src/test/scala/com/github/johnynek/paiges/PaigesTest.scala
Certainly after adding lineBreak in #29 (and possibly even before, I haven't checked), some expectations around equality are broken.
To fix these, we have to remember two bits of information around `Line`: we keep if the line should be flattened into space or line, and if the spaces after a line are absolute (from aligned) or relative (from nested).
This weakens the `deunioned` which was already private and only used for law checking. The problem is that two different `Doc` items are deunioned into the same set of Docs.
> Fix Ordering after we have align and lineBreak

- build.sbt
It's sort of ridiculous that we still have to do this.
The specific code comes from Cats' build (via ScalaCheck).
> This is a hack to enable imports in the console.

- core/src/main/scala/com/github/johnynek/paiges/Doc.scala
- core/src/test/scala/com/github/johnynek/paiges/Generators.scala
- core/src/test/scala/com/github/johnynek/paiges/PaigesTest.scala
take a look at this @coltfred 
I *think* this will be enough for opt-parse-applicative. It models this method:
https://github.com/bmjames/scala-optparse-applicative/pull/13/files#diff-9af4bcd927b95bd619209389ada92c30R95
which I think is always called with a doc constructed from one or a few strings.
In the worst case, we could add `tabulate(cols: List[(Doc, Doc)], leftWidth: Int)` and render the left side into a String and take the same approach, which will work for more cases perhaps.
> Add tabulate for simple and common table cases

- README.md
- core/src/main/scala/org/typelevel/paiges/Doc.scala
- core/src/test/scala/org/typelevel/paiges/PaigesTest.scala
Previously, bracketBy always used spaces when fitting the document on
a single line. In the context of codegen this is often not what you
want. Now, there is an optional argument to control this behavior.
(The distinction has to do with whether to use Doc.line or
Doc.lineBreak in the actual implementation.)
For example:
```scala
val prefix = Doc.text("say(")
val body = Doc.text("something somewhat long")
val suffix = Doc.text(")")
body.bracketBy(prefix, suffix).render(80)
// say( something somewhat long )
body.bracketBy(prefix, suffix, spaces = false).render(80)
// say(something somewhat long)
```
> Add an option to skip spaces on bracketBy.

- core/src/main/scala/org/typelevel/paiges/Doc.scala
- core/src/test/scala/org/typelevel/paiges/PaigesTest.scala
While a small interface to this library is nice, I think a special case for
horizontal concatenation is as justified as those for space and newline.
> Add 'cat' as analogy to 'stack' and 'spread'

- core/src/main/scala/org/typelevel/paiges/Doc.scala
- core/src/test/scala/org/typelevel/paiges/PaigesTest.scala
I think concatenation with space is just as common as with either empty or
newline.  This change adds more succinct syntax for this.  The analogous Haskell
library* also has syntax for this with '<+>'.  (It uses '<>' for our '+', and
'<$>' for our '/'.)
I don't care about the particular identifier, but I found having to type `foo space bar space baz` tiresome.
[*] https://hackage.haskell.org/package/wl-pprint-1.2/docs/Text-PrettyPrint-Leijen.html
> Add '&' as shorter syntax for 'space'

- core/src/test/scala/org/typelevel/paiges/PaigesTest.scala
We explicitly state that Text fields can't have newlines.
This change fixes a test that formerly had explicit newlines.
> Modify test with undefined behavior

- core/src/main/scala/org/typelevel/paiges/Chunk.scala
- core/src/main/scala/org/typelevel/paiges/Doc.scala
- core/src/test/scala/org/typelevel/paiges/PaigesScalacheckTest.scala
we have laziness now in one side of Union, but only rarely use it.
This instead makes a new AST node so we can use it exactly where we need it.
cc @seanmcl
> Add LazyDoc

- core/src/main/scala/org/typelevel/paiges/Doc.scala
This invariant makes sense, and the author of the code
clearly had it in mind since they added code comments
like "Note that first != second".
> Add comment about Union invariant

- core/src/main/scala/org/typelevel/paiges/Doc.scala
We assume the only use of (the referentially transparent) `generate`
should be cached via `evaluated`.  This obviates mistakes where
we throw away work by calling `generate` directly.
> Don't allow misuse of LazyDoc

- core/src/main/scala/org/typelevel/paiges/Chunk.scala
- core/src/main/scala/org/typelevel/paiges/Doc.scala
- core/src/test/scala/org/typelevel/paiges/PaigesScalacheckTest.scala
I'm not sure about this change, but it does eliminate
a potential programming mistake.  Typecasing is known
to be an effect in general, but here it seems harmless.
WDYT?
> Really hide the LazyDoc argument

- core/src/main/scala/org/typelevel/paiges/Doc.scala
- core/src/test/scala/org/typelevel/paiges/Generators.scala
- core/src/test/scala/org/typelevel/paiges/PaigesScalacheckTest.scala
- core/src/test/scala/org/typelevel/paiges/PaigesTest.scala
This change fixes invariants broken by `fill`, e.g. #112.  Note that using
`Concat` when making the `Union` is not sufficient, since flat `Doc`s can
be `Concat` nodes themselves, and thus we get left-associated `Concat` 
nodes all over the place in the existing code.  This fix locally associates them
without doing too much work.
> Maintain `Union` invariants in `fill`

- build.sbt
- version.sbt
The version number is now derived from the git commit.
> Remove unnecessary version.sbt

- core/src/main/scala/org/typelevel/paiges/Chunk.scala
- core/src/main/scala/org/typelevel/paiges/Doc.scala
- core/src/test/scala/org/typelevel/paiges/Generators.scala
- core/src/test/scala/org/typelevel/paiges/PaigesScalacheckTest.scala
- core/src/test/scala/org/typelevel/paiges/PaigesTest.scala
This adds two tests to LazyDoc and improves LazyDoc such that evaluated tail recursively fully evaluated the lazy doc into a non lazy doc. If we pass through another LazyDoc, we evaluate that as well.
> Improve LazyDoc a bit

- build.sbt
- core/src/main/scala-2.12-/org/typelevel/paiges/ScalaVersionCompat.scala
- core/src/main/scala-2.13+/org/typelevel/paiges/ScalaVersionCompat.scala
- core/src/main/scala/org/typelevel/paiges/Doc.scala
- core/src/test/scala/org/typelevel/paiges/PaigesScalacheckTest.scala
close #182 
This uses an sbt trick from cats to add some directories that are conditionally compiled on different versions of scala. The idea is that you make that object source compatible assuming the scala standard library.
> Use sbt tricks to use LazyList in 2.13, Stream before that

- .github/workflows/ci.yml
- build.sbt
The previous commit didn't run `sbt githubWorkflowGenerate`. This commit
fixes that so that the CI becomes green again.
> Update sbt-github-action worklows

- .github/workflows/ci.yml
- build.sbt
- docs/src/main/mdoc/intro.md
- project/plugins.sbt
Resolves https://github.com/typelevel/paiges/issues/339
This PR does a pretty naive migration of `tut` to `mdoc`.
Some differences in output:
```scala
// unbroken text from a String
val cat = Doc.text("cat")
// cat: org.typelevel.paiges.Doc = Doc(...)
// same as text, but using .toString first
val pair = Doc.str((1, 2))
// pair: org.typelevel.paiges.Doc = Doc(...)
```
```scala
// unbroken text from a String
val cat = Doc.text("cat")
// cat: Doc = Text(str = "cat")
// same as text, but using .toString first
val pair = Doc.str((1, 2))
// pair: Doc = Text(str = "(1,2)")
```
It looks like we weren't using the output of tut anywhere in the previous build?
Maybe I am missing something... 🤔
> Migrate to mdoc

- core/src/main/scala/org/typelevel/paiges/Doc.scala
- core/src/test/scala/org/typelevel/paiges/PaigesScalacheckTest.scala
Doc.text forces a single version of line parsing, and it's the only way to convert a `String` to a `Doc`. Sometimes, however, you might want `hardLine`s and not `line` which when flattened becomes a space.
> add Doc.textWithLine for controlling how lines are parsed
