typelevel/paiges

cats/src/main/scala/com/github/johnynek/paiges/instances.scala, cats/src/test/scala/com/github/johnynek/paiges/LawTests.scala, core/src/main/scala/com/github/johnynek/paiges/Doc.scala, core/src/test/scala/com/github/johnynek/paiges/Generators.scala, core/src/test/scala/com/github/johnynek/paiges/PaigesTest.scala
This commit does a few small Doc refactors, but is mainly focusesd
around two things:
1. Add .hashCode to Doc
2. Do law-checking for Order and Monoid instances
There is too much ceremony around laws (ugh) but for now I think this
is the right way forward.
=> Hash code + law-checking.

core/src/main/scala/com/github/johnynek/paiges/Doc.scala, core/src/test/scala/com/github/johnynek/paiges/PaigesTest.scala
I added a few tests. I sketched (but failed) to add a function called `maxWidth`. The idea is that it returns the smallest number w such that `doc.render(v) == doc.render(w)` for all `v > w`.
I failed to implement that correctly.
If we have that function, we can test more completely since we can test that if two things render the same up to the max width, we know the are the same (it gives a brute-force equals method). It would be nice to have that.
Also, I think it may be that your algorithm for comparison is correct IF we construct unions every way except the way fill does, which is lawful according to the paper, but a weaker law than I think your algorithm assumes. We could possible sacrifice fill as a combinator, or implement it so that it obeys the invariant we want, and I think we …
=> Add some test, fix some minor bugs

core/src/main/scala/com/github/johnynek/paiges/Doc.scala, core/src/test/scala/com/github/johnynek/paiges/PaigesTest.scala
repeat tests can be VERY slow. I have not debugged it but it is kind of the worst case: identical values but different structures, and we have repeated internal structure.
We could imagine memoization helping in such cases, but I just turned down the size of the tests.
=> Add repeat

core/src/main/scala/com/github/johnynek/paiges/Doc.scala, core/src/test/scala/com/github/johnynek/paiges/PaigesTest.scala
more stack safety for our cruel jvm masters.
=> Make flatten and flattenOption stack-safe

core/src/test/scala/com/github/johnynek/paiges/PaigesTest.scala
Here we add the laws the algorithm is expecting to be true about flatten and union. I'm adding these before I experiment with extending flattening so I can make sure we don't violate any assumption of the algorithm.
=> Add more union and flatten laws

core/src/main/scala/com/github/johnynek/paiges/Doc.scala
=> add flattenBool to reassociate in fill

README.md, benchmark/src/main/scala/PaigesBenchmark.scala, build.sbt, cats/src/main/scala/com/github/johnynek/paiges/Document.scala, cats/src/main/scala/com/github/johnynek/paiges/instances.scala, cats/src/test/scala/com/github/johnynek/paiges/LawTests.scala, core/src/main/scala/com/github/johnynek/paiges/Chunk.scala, core/src/main/scala/com/github/johnynek/paiges/Doc.scala, core/src/main/scala/com/github/johnynek/paiges/DocTree.scala, core/src/main/scala/com/github/johnynek/paiges/Fix.scala, core/src/main/scala/com/github/johnynek/paiges/Step.scala, core/src/main/scala/com/github/johnynek/paiges/package.scala, core/src/test/scala/com/github/johnynek/paiges/Generators.scala, core/src/test/scala/com/github/johnynek/paiges/JsonTest.scala, core/src/test/scala/com/github/johnynek/paiges/PaigesTest.scala, docs/src/main/tut/intro.md
This commit changes the package in the build, source files, README, docs, etc.
If we wanted to use a different package name from `org.typelevel.packages` as the package then this PR will need to be amended.
=> Move from com.github.johnynek to org.typelevel.

core/src/main/scala/org/typelevel/paiges/Doc.scala, core/src/test/scala/org/typelevel/paiges/PaigesTest.scala
fixes #45 
review @coltfred @non ?
=> Fix Doc.char for newline

README.md
Assuming you'll still have me.
=> Add me as a maintainer.

README.md
we are alphabetizing by last name
=> reorder names in README

.gitignore, build.sbt, cats/src/main/scala/org/typlevel/paiges/instances.scala, cats/src/test/scala/org/typelevel/paiges/LawTests.scala, core/src/main/scala/org/typelevel/paiges/Chunk.scala, core/src/test/scala/org/typelevel/paiges/PaigesTest.scala, project/plugins.sbt, version.sbt
These are all changes we need to get the release working.
=> Pre-release changes

README.md, build.sbt
This commit also fixes the console, which was still broken
(and which I was trying to use to test the README).
=> Update the README for 0.1.0.

build.sbt
=> We need this for isolated imports to work in tut.

cats/src/test/scala/org/typelevel/paiges/DocumentTests.scala, core/src/test/scala/org/typelevel/paiges/PaigesTest.scala
Notably this adds real tests for Document (which is a fairly
simple type class, but one would should be sure to actually test).
=> Add some tests to improve coverage.

core/src/main/scala/org/typelevel/paiges/Chunk.scala, core/src/main/scala/org/typelevel/paiges/Doc.scala, core/src/test/scala/org/typelevel/paiges/PaigesTest.scala
=> `trim` documents

core/src/main/scala/org/typelevel/paiges/Document.scala, core/src/test/scala/org/typelevel/paiges/DocumentTests.scala
Follows the pattern codified by https://github.com/mpilquist/simulacrum
=> Add implicit Document ops

core/src/main/scala/org/typelevel/paiges/Chunk.scala, core/src/test/scala/org/typelevel/paiges/PaigesTest.scala
I'm not sure about the performance implications of this CR, but at least the tests pass.  I don't know how to run the benchmarker.  Any advice?
=> Make `trim` satisfy laws 

build.sbt, cats/src/main/scala/org/typelevel/paiges/CatsDocument.scala, cats/src/test/scala/org/typelevel/paiges/LawTests.scala, project/build.properties, project/plugins.sbt
cats updated to 1.0.1
scalajs updated to 0.6.21
sbt updated to 0.13.16
=> cats, scalajs and sbt update

core/src/test/scala/org/typelevel/paiges/Generators.scala
=> Add counterexample shrinking

core/src/main/scala/org/typelevel/paiges/Chunk.scala
just clearing up that these aren't used.
=> Remove some unneeded bindings

core/src/test/scala/org/typelevel/paiges/Generators.scala
follow up to #133 since I noticed we aren't generating calls to intercalate (only with specific separators).
=> Add intercalate to generated folds

core/src/main/scala/org/typelevel/paiges/Doc.scala, core/src/test/scala/org/typelevel/paiges/PaigesScalacheckTest.scala
these are two useful functions I noticed the haskell implementation added, but we didn't.
=> add hang and indent, combinators from the haskell implementation

cats/shared/src/main/scala/org/typelevel/paiges/instances.scala, cats/shared/src/test/scala/org/typelevel/paiges/LawTests.scala
This adds Monoid and Eq for Style in the cats package.
=> Add Monoid and Eq for Style

build.sbt
Previously we had a hand-coded (and hand-maintained) strategy that
would fail every time we released a new minor (or major) version of
Paiges. Now, we have a fairly reasonable heuristic that ensures we are
preserving compatibility across versions.
We aren't being as strict as we might want when bumping the minor or
major versions (we could be requiring compatibility with the
chronologically last release) but that would require a bigger change
and is outside the scope of this work for now.
(This isn't pressing because 0.x releases don't promise compatibility
across minor versions, so we don't need to solve this until 1.0.)
=> Future-proof the previous version detection.

build.sbt
=> Set crossScalaVersion to 2.11 on native

build.sbt
context is scala/community-build#1033
supersedes #221
=> ScalaTest version bumps

build.sbt
=> various updates and consolidation

build.sbt, project/plugins.sbt
The following build error is suspicious:
```
[error] (catsJS / Test / fastOptJS) java.io.IOException: Failed to deserialize /home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/typelevel/cats-core_sjs1_2.13/2.1.0/cats-core_sjs1_2.13-2.1.0.jar:/cats/syntax/package$hash$.sjsir
```
=> Scala.js 1

build.sbt
=> Update to scala 3 M3
